### ISSUE TITLE
document implications of caching values

### ISSUE THREAD

**Issue by ktdreyer** [ansible-collections/cloud.common#14]
This hard-codes `~/.ansible/tmp/turbo_mode.socket`

Can we please document what happens in the following scenarios?

A. My teammate and I invoke two Ansible playbooks on the same system at the same time (will they collide?)

B. I invoke a playbook that quickly uses two completely separate "cached" SDK client connections with different privileges (The daemon shuts down with 15 seconds of inactivity, but what if I'm running tasks faster than that?).

**Comment by goneri** [comment]
Hi @ktdreyer,

I've started a documentation PR to answer your questions, and another one to reduce the visibility of the cache. Your feedback are welcome.
